name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git remote add hf https://huggingface.co/spaces/dusanisbaek/snu-cxi-ux-eval
        git remote set-url hf https://dusanisbaek:$HF_TOKEN@huggingface.co/spaces/dusanisbaek/snu-cxi-ux-eval
        
        git push hf main --force
        
        echo "✅ Successfully synced to Hugging Face Space!"
