name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    if: github.event_name == 'push'  # PR에서는 실행하지 않음
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 전체 히스토리 가져오기
        
    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Git 설정
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Hugging Face Space를 원격 저장소로 추가
        git remote add hf https://huggingface.co/spaces/dusanisbaek/snu-cxi-ux-eval
        
        # HF 토큰으로 인증 설정
        git remote set-url hf https://dusanisbaek:$HF_TOKEN@huggingface.co/spaces/dusanisbaek/snu-cxi-ux-eval
        
        # Hugging Face Space에 푸시
        git push hf main --force
        
        echo "✅ Successfully synced to Hugging Face Space!"
